environment: "dev"

exchange:
  default: "binance"
  binance:
    rest_url: "https://fapi.binance.com"
    ws_url: "wss://fstream.binance.com/ws"
    symbol: "BTCUSDT"
    leverage: 10
    testnet: true

data:
  storage_path: "./data"
  timeseries_db: "sqlite" # dev: sqlite, prod: clickhouse
  archive_path: "./storage/archive"

messaging:
  backend: "redis"
  redis_url: "redis://localhost:6379/0"

risk:
  max_spread_pct: 0.15
  min_liquidity: 0.5
  slippage_limit: 0.03

logging:
  level: "INFO"
  log_path: "./logs"

model:
  active_model_version: "scalping_v1"
  inference_endpoint: "http://localhost:8000/predict"

telegram:
  use_alerts: true

labeling:
  horizon_s: 5
  threshold_bp: 10 # 10 bp = 0.10%
  neutral_band: true

features:
  trade_windows_s: [0.5, 1, 5] # 문서용. 실제는 trade_features 내부에서 처리
  liquidations:
    windows_s: [30, 60]
    big_notional: 100000 # 100k USDT 기준 대형 청산
  orderbook:
    agg_K: 5 # 집계형에서 ±1~±K% 밴드 사용

paths:
  features_out: data/features/features_1s.parquet
